### ISSUE TITLE
Add author to DITA prolog section

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/dita-prolog-updater#1]
The first time a DITA topic is created in Oxygen, the plugin could add information about the current author:

https://www.oxygenxml.com/dita/1.3/specs/langRef/base/author.html

And on subsequent times it could add information about the last author who modified it.
Basically it would look in the DITA topic, if it does not have a prolog section it would add it and if it has a prolog section it would update it to contain the author information:

        <prolog>
          <author type="creator">Jane</author>
          <author type="contributor">John</author>
        </prolog>

The plugin would add a listener to be notified when a WSEditor is opened.
On all opened WSEditor's it can add a save listener. 
The listener has callbacks before each save operation. If the "ro.sync.exml.workspace.api.editor.WSEditorBase.isNewDocument()" returns true, then it is a new file and on the first save we need to set the author with type="creator".
If the document is not new, we can add an author of type contributor to it.

There is a configuration page where the end user can set their author name to be used.

**Comment by DunaMariusCosmin** [comment]
Fixed in: a006907c3fff2385b1eaf2a6264eab841cac67de
