### ISSUE TITLE
Add created and revised dates to DITA prolog section

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/dita-prolog-updater#2]
The DITA prolog can also have a created and a revised date:

https://www.oxygenxml.com/dita/1.3/specs/langRef/base/created.html
https://www.oxygenxml.com/dita/1.3/specs/langRef/base/revised.html

Again, depending on weather the topic is saved for the first time or on subsequent times, the prolog could be updated to contain this information every time the document is saved.

**Comment by DunaMariusCosmin** [comment]
Fixed in: 0d398c0a61f69f73cedf6e1d63604c634de666b8
